//
// Created by david on 08.01.21.
//

#ifndef HDVENT_CONTROL_SENSOR_SETTINGS_H
#define HDVENT_CONTROL_SENSOR_SETTINGS_H
float const PRESSURE_FLOW_CONVERSION = -771.49; // ml*s^-1 / mbar
float const PRESSURE_FLOW_CONVERSION_OFFSET = 0.042;

#endif //HDVENT_CONTROL_SENSOR_SETTINGS_H
